### ISSUE TITLE
JavaScript best practice principles (DRY, KISS, YAGNI) 

### ISSUE THREAD

**Issue by SaidRasinlic** [HamzaAnwar1998/ToDo-List-Using-Webpack#5]
## No issues found 👍🏼 

**Clean code, understandable, and easy to maintain, such a great job you did! Nice work keep it up 💯 🔥**

![](https://www.reactiongifs.us/wp-content/uploads/2018/08/giphy-5-2.gif)

**Comment by HamzaAnwar1998** [comment]
Thank you. I really appreciate your effort in reviewing my code
