### ISSUE TITLE
Code review: 04. 07. 2022

### ISSUE THREAD

**Issue by flower-v-codes** [HamzaAnwar1998/ToDo-List-Using-Webpack#6]
## JavaScript
* I think you did a good job in writing your JavaScript code, I couldn't find any issue
* optional/preference: I think you can take your JavaScript code apart into 1-2 more module files

**Comment by flower-v-codes** [comment]
## HTML & CSS
* I didn't find any issues in the HTML and CSS file
* optional/suggestion: It is useful to put box-sizing: border-box in the CSS file, as it helps when it comes to sizing elements  
  *  border-box tells the browser to account for any border and padding in the values you specify for an element's width and height. If you set an element's width to 100 pixels, that 100 pixels will include any border or padding you added, and the content box will shrink to absorb that extra width. This typically makes it much easier to size elements. 
```
* {
 box-sizing: border-box;
}
```

**Comment by flower-v-codes** [comment]
## README
* It would be nice if we can see a live site URL link to the project

**Comment by HamzaAnwar1998** [comment]
Thank you! I really appreciate your feedback
